import { defineCollection, reference } from 'astro:content';
import { file, glob } from 'astro/loaders';
import { z } from 'astro/zod';

// One JSON file per event (src/data/events/<id>.json) rather than one big
// array, so the /admin panel can add or edit an event as a single-file
// change in its pull request.
const events = defineCollection({
  loader: glob({ pattern: '*.json', base: 'src/data/events' }),
  schema: ({ image }) =>
    z.object({
      id: z.string(),
      title: z.string(),
      summary: z.string(),
      description: z.string(),
      location: z.string(),
      startDate: z.coerce.date(),
      endDate: z.coerce.date(),
      // Both optional: an event without them simply has no early bird.
      earlyBirdPrice: z.number().optional(),
      earlyBirdDeadline: z.coerce.date().optional(),
      price: z.number(),
      // Optional price for two people signing up together.
      couplePrice: z.number().optional(),
      currency: z.string().default('CLP'),
      // A path relative to this event's JSON file — see src/data/images/events/.
      // Optional: without one the site shows events/default.jpg (generated by
      // scripts/generate-default-event-image.mjs) — see eventImage().
      image: image().optional(),
      tags: z.array(z.string()).default([]),
      hostIds: z.array(z.string()).default([]),
      featured: z.boolean().default(false),
      // Set to false to take an event off the site (listing, homepage and
      // its own page) without deleting its data; flip back to republish.
      published: z.boolean().default(true),
    }),
});

// Bios run long and read better as prose than as escaped JSON strings, so
// team members are one Markdown file each (frontmatter for the structured
// fields, body for the bio) rather than flat JSON like the other collections.
const team = defineCollection({
  loader: glob({ pattern: '*.md', base: 'src/data/team' }),
  schema: ({ image }) =>
    z.object({
      name: z.string(),
      role: z.string(),
      // Short third-person blurb (~70 words) for the homepage team cards —
      // same text as the facilitator's "¿Quiénes somos?" Instagram card.
      // The body stays the long first-person story shown on /team.
      summary: z.string().optional(),
      // A path relative to this file — see src/data/images/team/.
      // Swap in the real photo under the same filename to replace it.
      photo: image(),
      specialties: z.array(z.string()).default([]),
      social: z
        .object({
          instagram: z.url().optional(),
          website: z.url().optional(),
        })
        .default({}),
    }),
});

const testimonials = defineCollection({
  loader: file('src/data/testimonials.json'),
  schema: z.object({
    id: z.string(),
    quote: z.string(),
    name: z.string(),
    event: z.string(),
  }),
});

const blog = defineCollection({
  loader: glob({ pattern: '**/*.md', base: 'src/content/blog' }),
  schema: ({ image }) =>
    z.object({
      title: z.string(),
      summary: z.string(),
      pubDate: z.coerce.date(),
      // A path relative to this file — see src/content/blog/images/.
      cover: image().optional(),
      tags: z.array(z.string()).default([]),
      // Set to false to take a post off the site without deleting it; when
      // no post is published, the Blog nav link disappears too.
      published: z.boolean().default(true),
      // Usually one of our own facilitators (referenced by team id, so their
      // name/photo/bio stay in sync automatically). A post from someone
      // outside the team roster falls back to typing their details inline.
      author: z.union([
        reference('team'),
        z.object({
          name: z.string(),
          bio: z.string().optional(),
          photo: image().optional(),
        }),
      ]),
    }),
});

// One Markdown file per question (src/content/faq/), so answers can carry
// links and paragraphs; `order` sets their position on /faq.
const faq = defineCollection({
  loader: glob({ pattern: '*.md', base: 'src/content/faq' }),
  schema: z.object({
    question: z.string(),
    order: z.number(),
  }),
});

export const collections = { events, team, testimonials, blog, faq };
